### ISSUE TITLE
TODO V1.0.4

### ISSUE THREAD

**Issue by Mathu-lmn** [Mathu-lmn/mth-rc#13]
- [x] Fix franklin's voice
- [x] Ability to self destruct when on camera
- [x] Delete blip on self destruct
- [x] Support for qb-inventory
- [x] Fix modkit
- [x] Add short-circuit on water 
- [x] Add recall option
- [x] Better Explosion

**Comment by Mathu-lmn** [comment]
Ready to publish
