### ISSUE TITLE
TODO : V1.0.5

### ISSUE THREAD

**Issue by Mathu-lmn** [Mathu-lmn/mth-rc#17]
- [ ] Fix shooting when using controller / RC
- [ ] Disable entering another vehicle while RC is out
- [ ] Add pickup with key

**Comment by TayMcKenzieNZ** [comment]
Hallo PLS halp
