### ISSUE TITLE
TODO V1.0.2

### ISSUE THREAD

**Issue by Mathu-lmn** [Mathu-lmn/mth-rc#2]
- [x] Fix being able to enter the RC
- [x] Fix movement when max distance is reached
- [x] Add blip on the map to find the RC (ID : 647)
- [x] Fix network owning issues
